# vim:ft=kitty

## name:     Catppuccin Kitty Mocha (Darker)
## based on: Catppuccin Mocha

foreground              #cdd6f4
background              #15151f
selection_foreground    #15151f
selection_background    #e6c8c2

cursor                  #f5e0dc
cursor_text_color       #15151f

url_color               #f5e0dc

active_border_color     #9aa2d4
inactive_border_color   #535667
bell_border_color       #e3cc92

wayland_titlebar_color system
macos_titlebar_color system

active_tab_foreground   #11111b
active_tab_background   #b893e6
inactive_tab_foreground #cdd6f4
inactive_tab_background #13131b
tab_bar_background      #0d0d13

# Marks
mark1_foreground #15151f
mark1_background #9aa2d4
mark2_foreground #15151f
mark2_background #b893e6
mark3_foreground #15151f
mark3_background #64b8d2

# 16 colors (unchanged)
color0  #45475a
color8  #585b70
color1  #f38ba8
color9  #f38ba8
color2  #a6e3a1
color10 #a6e3a1
color3  #f9e2af
color11 #f9e2af
color4  #89b4fa
color12 #89b4fa
color5  #f5c2e7
color13 #f5c2e7
color6  #94e2d5
color14 #94e2d5
color7  #bac2de
color15 #a6adc8
